# Site settings
title: Seera Networks
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://seeranetworks.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
version: 3.2.1

source: ./_source
permalink: pretty

# Pretty URL
# permalink: "posts/:title"

# Collections
collections:
  members:
    output: true
    _hide_content: true
  network:
    output: true
    _hide_content: true
  news:
    output: true

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "network"
    values:
      layout: "category"
  -
    scope:
      path: ""
      type: "news"
    values:
      layout: "post"

# sass
sass:
    style: :compressed
