# Site settings
title: Seera Networks
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
version: 3.2.1

# Pretty URL
# permalink: "posts/:title"

# Collections
collections:
  members:
    output: true
  network:
    output: true
  testimonials:
    output: false
  news:
    output: true

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "network"
    values:
      layout: "category"
  -
    scope:
      path: ""
      type: "testimonials"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "news"
    values:
      layout: "post"

# sass
sass:
    style: :compressed
